### ISSUE TITLE
How can you make each card to take less space?

### ISSUE THREAD

**Issue by SelaO** [sidevesh/react-native-material-cards#1]
There's a lot of wasted space here: 

![image](https://user-images.githubusercontent.com/21977571/29473432-7b64675e-8460-11e7-972f-92d5e9cb3610.png)

Is there a way to make it more condensed?

This is the code:

```
            <Card style={styles.card}>
                <CardTitle title={Title} subtitle={"By: " + Author + " Sent time:" + SendTimeUtc} />
                <CardContent text={Body} />
            </Card>
```

**Comment by sidevesh** [comment]
The specifications for the cards is based on [material design guidelines](https://material.io/guidelines/components/cards.html) and while I agree that there is a lot of wasted space, the library will have to follow the said guidelines. You are free to give your own style object as prop to the components and see if that brings it to your requirements.

**Comment by SelaO** [comment]
I tried to change the `height` and `minHeight` but those didn't help, what other style keys can help?

**Comment by sidevesh** [comment]
See the source code of each components, all have their corresponding stylesheet in bottom, you will have to change padding values mostly.
