### ISSUE TITLE
Getting - undefined is not an object (evaluating _react2.PropTypes.func

### ISSUE THREAD

**Issue by kasiselvamk** [sidevesh/react-native-material-cards#10]
it looks like react latest version removed such _react2.PropTypes.func.
after i enabled below. 

Touchable.propTypes = {
  _enabled: React.PropTypes.func,_
  onPress: PropTypes.func.isRequired,
  style: View.propTypes.style,
  children: PropTypes.node.isRequired,
};

any work around...

**Comment by asciifaceman** [comment]
To fix this locally for now edit `Touchable.js` in the src dir:

`import React, { PropTypes } from 'react';`

becomes

```
import React from 'react';
import PropTypes from 'prop-types';
```

I'll open a PR with the perm fix if the maintainer is still around

**Comment by asciifaceman** [comment]
Nix that, it is fixed already in the source. @SiDevesh needs to update NPM

**Comment by AlMel3000** [comment]
Similar error.
NPM is updated.

```
undefined is not an object (evaluating '_react.PropTypes.func')
<unknown>
    C:\Users\almel\Documents\development\Notarization\node_modules\react-native-material-cards\src\Touchable.js:41:21
loadModuleImplementation
```

etc

**Comment by mcbroh** [comment]
Same error here.... NPM has been updated.

**Comment by asciifaceman** [comment]
I meant the person who wrote the library needs to update upstream NPM

**Comment by smitthakkar1** [comment]
Any workaround to @AlMel3000 's problem ?

**Comment by sidevesh** [comment]
npm package updated, issue should be resolved now, sorry for delay.npm package updated, issue should be resolved now, sorry for delay.
