### ISSUE TITLE
issue in cardImage 

### ISSUE THREAD

**Issue by rahulbhankar786** [sidevesh/react-native-material-cards#12]
![screenshot_1514876030](https://user-images.githubusercontent.com/33485869/34476624-6fa24094-efb8-11e7-9aff-75820ab471f4.png)

this error is showing white using this library. please resolve this issue and reply me. thanks

**Comment by bartslootweg** [comment]
It has something to do with the title property. But If you remove 'title' from CardImage you will probably run into an error regarding resizeMethod. In that case you will need to update line 20 of CardImage.js from:

`<Image source={this.props.source} resizeMode={["stretch", this.props.resizeMode]} resizeMethod={["resize", this.props.resizeMethod]} style={[styles.imageContainer,  {height: this.state.calc_height}]}>`

to:
`<Image source={this.props.source} resizeMode={this.props.resizeMode || "stretch"} resizeMethod={this.props.resizeMethod || "resize"} style={[styles.imageContainer,  {height: this.state.calc_height}]}>`

I think the required react-native version is out of date

**Comment by sidevesh** [comment]
Fixed with #8 being merged.
