### ISSUE TITLE
Issue in using the library (using github sample)

### ISSUE THREAD

**Issue by jfrshd** [sidevesh/react-native-material-cards#15]
TypeError in D:\My Projects\Mobile Development (react-native)\kafila\node_modules\react-native-material-cards\src\Touchable.js: D:/My Projects/Mobile Development (react-native)/kafila/node_modules/react-native-material-cards/src/Touchable.js: Duplicate declaration "ViewPropTypes"
  at D:\My Projects\Mobile Development (react-native)\kafila\node_modules\react-native-material-cards\src\Touchable.js:7:2
processBundleResult
    BundleDownloader.java:259
access$200
    BundleDownloader.java:35
onChunkComplete
    BundleDownloader.java:195
emitChunk
    MultipartStreamReader.java:76
readAllParts
    MultipartStreamReader.java:154
processMultipartResponse
    BundleDownloader.java:179
access$100
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:148
c
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

**Comment by glynnallen1704** [comment]
I have fixed this and submitted a pull request.
