### ISSUE TITLE
Error Duplication declaration "ViewPropTypes" at Touchable.js

### ISSUE THREAD

**Issue by louiskueh** [sidevesh/react-native-material-cards#16]
`import {
  ViewPropTypes,
  TouchableOpacity,
  TouchableNativeFeedback,
  ViewPropTypes
} from 'react-native';`

**Comment by RafaO** [comment]
Hi! Why was this closed? I have same issue too.

**Comment by louiskueh** [comment]
Hi,  Please view pull request #14
