### ISSUE TITLE
How to add onClick prop to cards?

### ISSUE THREAD

**Issue by balaji-dr** [sidevesh/react-native-material-cards#19]
I need a clickable card to perform an action. Buttons are there but I need to click the entire card.

**Comment by ozanmanav** [comment]
You can use TouchableOpacity like that;
`  <TouchableOpacity
                onPress={item => {
                  this.goToDetailScreen(item);
                }}
              >
                <Card>
                  <CardImage
                    source={{ uri: "http://placehold.it/480x270" }}
                    title={item.name}
                  />
                  <CardTitle
                    title={item.windowstart}
                    subtitle={item.location.name}
                  />
                </Card>
              </TouchableOpacity>`

**Comment by Lythenas** [comment]
FYI I created a pull request that should make this a bit nicer. #21
