### ISSUE TITLE
Source code for the cards in the example picture

### ISSUE THREAD

**Issue by Lythenas** [sidevesh/react-native-material-cards#23]
Hey,
first of all thanks for this library. It saved me quite some time.

While it's probably not difficult to recreate. Can you publish the code you used to create the cards in the picture in the readme? Maybe as a runnable example. This would be useful to use for testing. I already opened two pull request but I can't easily test if my changes mess something else up.

**Comment by sidevesh** [comment]
Hi, sorry for really late reply on this.
If it helps, you can find the source code for those here https://github.com/SiDevesh/MaterialCardsDevelop
