### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JanZumdick** [sidevesh/react-native-material-cards#37]
Code from Example. (Readme)

Give me an Error:
![Examp1](https://user-images.githubusercontent.com/58948686/114373890-5a200100-9b83-11eb-84e3-ff474e819dac.png)

**Comment by sidevesh** [comment]
Looks like ViewPropTypes is not present in your react-native version, maybe you are using too old of a version of react-native.
Try updating react-native in your project.
Closing since this issue is external to this library.
