### ISSUE TITLE
Library doesn't run due to the React version

### ISSUE THREAD

**Issue by illright** [sidevesh/react-native-material-cards#4]
I currently have React `16.0.0-beta.5` installed, which is the default version that comes with React Native `0.49.5`. Your project dependencies state that React `>=15.3.1` is required, but for some reason, React 16 is incompatible. NPM warned me about an unmet peer dependency and the application errors with this message:
```
undefined is not an object (evaluating '_react.PropTypes.func')
<unknown>
    Touchable.js:41:21
loadModuleImplementation
    require.js:178:12
guardedLoadModule
    require.js:130:36
_require
    require.js:110:20
<unknown>
...
```

How can I fix this error?

**Comment by sidevesh** [comment]
Have merged your PR. Thanks!
