### ISSUE TITLE
Update NPM Package 

### ISSUE THREAD

**Issue by BradleyFaught** [sidevesh/react-native-material-cards#7]
Update NPM Package - still using old prop-type

**Comment by craigwheeler** [comment]
confirmed getting same error ... 

![samsung galaxy s6 - 6 0 0 - api 23 - 1440x2560 1440x2560 640dpi - 192 168 58 101 2017-12-04 10-09-36](https://user-images.githubusercontent.com/7518899/33559630-68e519aa-d8db-11e7-8a2f-1c607b93fab7.png)

**Comment by anisjonischkeit** [comment]
until he updates the package on npm, just use `yarn add https://github.com/SiDevesh/React-Native-Material-Cards` or `npm install --save https://github.com/SiDevesh/React-Native-Material-Cards`

**Comment by sidevesh** [comment]
npm package updated, issue should be resolved now, sorry for delay.
